CREATE TABLE IF NOT EXISTS MEMBERS (
  MNAME    VARCHAR(50)  NOT NULL,
	PWD      VARCHAR(100) NOT NULL,

	PRIMARY KEY(MNAME)
);

CREATE TABLE IF NOT EXISTS AUTHORITIES (
    MNAME     VARCHAR(50)  NOT NULL,
    AUTHORITY VARCHAR(50)  NOT NULL,

    PRIMARY KEY(MNAME)
);

-- TODO : #2 change password column value
MERGE INTO MEMBERS VALUES ( 'admin' , HASH('SHA256', STRINGTOUTF8('admin' ), 1024) );
MERGE INTO MEMBERS VALUES ( 'member', HASH('SHA256', STRINGTOUTF8('member'), 1024) );
MERGE INTO MEMBERS VALUES ( 'guest' , HASH('SHA256', STRINGTOUTF8('guest' ), 1024) );

MERGE INTO AUTHORITIES VALUES ( 'admin' , 'ROLE_ADMIN'  );
MERGE INTO AUTHORITIES VALUES ( 'member', 'ROLE_MEMBER' );
MERGE INTO AUTHORITIES VALUES ( 'guest' , 'ROLE_GUEST'  );
